### PR TITLE
removed dependency on interactive markers

### PR DESCRIPTION
**Pull request by asaini89**
Removed dependency on interactive markers. This library is used by people package

### CODE REVIEW

**Review by efernandez — CHANGES_REQUESTED** [review]
Also remove it from here: https://github.com/clearpathrobotics/wu_ros_tools/blob/hydro/wu_ros_tools/package.xml#L15

**Comment by asaini89** [comment]
Done. Ping

**Comment by asaini89** [comment]
Done, can I please get a quick review on this.

**Review by efernandez — APPROVED** [review]
:+1:

**Review by servos — APPROVED** [review]

**Pull request merged**
